name: SkyWars
main: skywars.SkyWars
version: 0.1
author: [EpicSaxGuy, MrTwixo, Guitou388]
commands:
    skywars:
      description: Commande principal
    skybool:
        description: Tp dans le skywars
    joueurs:
        description: Liste des joueurs dans l'instance
permissions:
  skywars.*:
    description: Gives access to all swr commands
    default: true
    children:
      swr.enter: true
  skywars.enter:
    description: Gives access to the swr join and quit commands
    default: true