name: SkyWars
main: skywars.SkyWars
version: 0.1
commands:
    heal:
        description: Récupérer la vie
    list:
        description: Lister les joueurs
    count:
        description: Lancer la partie