name: SkyWars
main: skywars.SkyWars
version: 0.1
commands:
    heal:
        description: Récupérer la vie
    skybool:
        description: Tp dans le skywars
    hub:
        description: Tp au loby
    pvp:
        description: Tp au choix de classe