name: SkyWars
main: skywars.SkyWars
version: 0.1
author: [EpicSaxGuy, MrTwixo, Guitou388]
commands:
    skywars:
      description: Commande principal
    joueurs:
        description: Liste des joueurs dans l'instance