name: SkyWars
main: skywars.SkyWars
version: 0.1
commands:
    heal:
        description: Récupérer la vie
    meteo:
        description: Donne la météo
    skybool:
        description: Tp dans le skywars